base = "plants::name"

[[rulesets]]
[rulesets.rules]
"{singular}" = "{singular}"
"{plural}" = "{plural}"

[[rulesets]]
name = "singular"
[rulesets.rules]
"abaca tree" = "蕉麻树"
"acacia" = "刺槐"
"alder" = "桤树"
"alfalfa" = "苜蓿"
"almond tree" = "扁桃树"
"apple tree" = "苹果树"
"apricot tree" = "杏树"
"arrow bamboo" = "箭竹"
"artichoke" = "洋蓟"
"ash" = "白蜡树"
"asparagus" = "芦笋"
"avocado tree" = "鳄梨树"
"baby toes succulent" = "幼趾多肉"
"bambara groundnut plant" = "班巴拉花生植株"
"banana tree" = "香蕉树"
"barley" = "大麦"
"bayberry tree" = "杨梅树"
"beet plant" = "甜菜植株"
"bentgrass" = "糠穗草"
"bilberry bush" = "越橘灌木"
"birch" = "桦树"
"bitter melon vine" = "苦瓜藤"
"bitter orange tree" = "苦橙树"
"bitter vetch" = "苦野豌豆"
"blackberry bush" = "黑莓灌木"
"black-cap" = "黑菇"
"blade weed" = "刀刃草"
"bloated tuber" = "膨地根"
"blood amaranth" = "血苋"
"blood thorn" = "血荆棘"
"blueberry bush" = "蓝莓灌木"
"blue sedge" = "蓝苔莎"
"broad bean plant" = "蚕豆植株"
"bubble bulb" = "泡泡球茎"
"buckwheat" = "荞麦"
"cabbage" = "卷心菜"
"cacao tree" = "可可树"
"candlenut" = "石栗"
"caper bush" = "刺山柑灌木"
"carambola tree" = "杨桃树"
"carpetgrass" = "地毯草"
"cashew tree" = "腰果树"
"cassava" = "木薯"
"cattail" = "猫尾草"
"cave moss" = "洞穴苔藓"
"cave wheat" = "洞穴小麦"
"cedar" = "雪松"
"celery" = "芹菜"
"cherry tree" = "樱桃树"
"chestnut" = "板栗树"
"chickpea plant" = "鹰嘴豆植株"
"chicory" = "菊苣"
"citron tree" = "香橼树"
"cloudberry" = "云莓"
"coconut palm" = "椰棕榈"
"coffee tree" = "咖啡树"
"common reed" = "芦苇"
"cottongrass" = "棉草"
"cotton plant" = "棉花植株"
"cowpea plant" = "豇豆植株"
"cranberry vine" = "蔓越莓藤"
"cucumber vine" = "黄瓜藤"
"custard-apple tree" = "番荔枝树"
"dallisgrass" = "雀稗草"
"date palm" = "枣棕榈"
"desert lime tree" = "漠橘树"
"dimple cup" = "窝杯菇"
"dog's tooth grass" = "狗牙草"
"downy grass" = "羽绒草"
"dropseed grass" = "落籽草"
"durian tree" = "榴梿树"
"eggplant" = "茄子"
"elephant-head amaranth" = "象头苋"
"feather tree" = "羽毛树"
"fescue grass" = "细叶草"
"field sedge" = "田野莎草"
"finger lime tree" = "指橘树"
"finger millet plant" = "爪粟植株"
"fisher berry" = "渔夫浆果"
"flax plant" = "亚麻植株"
"floor fungus" = "地真菌"
"fonio plant" = "非尼奥米植株"
"foxtail millet plant" = "狐尾粟植株"
"fungiwood" = "真菌木"
"garden cress" = "水芹"
"garlic plant" = "大蒜植株"
"ginkgo tree" = "银杏树"
"glumprong" = "紫影树"
"goblin-cap" = "妖精菇"
"golden bamboo" = "金竹"
"grama" = "格兰马草"
"grape vine" = "葡萄藤"
"guava tree" = "番石榴树"
"hair grass" = "发草"
"hard wheat" = "硬质小麦"
"hazel tree" = "榛树"
"hedge bamboo" = "篱笆竹"
"hemp plant" = "大麻植株"
"hide root" = "匿茎草"
"highwood" = "极树"
"horned melon vine" = "刺角瓜藤"
"jute plant" = "黄麻植株"
"kaniwa" = "彩藜"
"kapok" = "木棉树"
"kenaf plant" = "洋麻植株"
"knotgrass" = "绳结草"
"kobold bulb" = "犬蜥球茎"
"kumquat tree" = "金橘树"
"larch" = "落叶松"
"leek" = "韭葱"
"lentil plant" = "扁豆植株"
"lesser yam plant" = "小山药植株"
"lettuce" = "生菜"
"lime tree" = "酸橙树"
"Longland grass" = "长岛草"
"long yam plant" = "长山药植株"
"lychee tree" = "荔枝树"
"macadamia tree" = "奶油果树"
"mahogany" = "褐芯树"
"maize plant" = "玉米植株"
"mango tree" = "芒果树"
"mangrove" = "红树"
"maple" = "枫树"
"marsh thistle" = "沼泽蓟"
"meadow-grass" = "甸草"
"meadowsweet" = "绣线菊"
"mountain avens" = "山蔷薇"
"muck root" = "淤曲根"
"mung bean plant" = "绿豆植株"
"muskmelon vine" = "甜瓜藤"
"needle grass" = "针草"
"nether-cap" = "下界菇"
"oak" = "橡树"
"oat" = "燕麦"
"olive tree" = "橄榄树"
"onion plant" = "洋葱植株"
"orange tree" = "橘子树"
"papaya tree" = "番木瓜树"
"papyrus sedge" = "纸莎草"
"paradise nut tree" = "天堂果树"
"parsnip plant" = "防风草植株"
"passion fruit vine" = "百香果藤"
"peach tree" = "桃树"
"peanut plant" = "花生植株"
"pea plant" = "豌豆植株"
"pearl millet plant" = "珍珠粟植株"
"pear tree" = "白梨树"
"pebble plant" = "生石花植株"
"pecan tree" = "碧根果树"
"pendant amaranth" = "吊坠苋"
"pepper plant" = "胡椒植株"
"persimmon tree" = "柿树"
"pig tail" = "猪尾草"
"pine" = "针松"
"pineapple plant" = "菠萝植株"
"plump helmet" = "肉盔菇"
"plum tree" = "李树"
"pomegranate tree" = "石榴树"
"pomelo tree" = "蜜柚树"
"potato plant" = "马铃薯植株"
"prickle berry" = "刺莓"
"purple amaranth" = "紫苋"
"purple moor grass" = "紫泽草"
"purple yam plant" = "紫薯植株"
"quarry bush" = "矿场灌木"
"quinoa" = "藜麦"
"radish plant" = "小萝卜植株"
"rambutan tree" = "红毛果树"
"ramie plant" = "苎麻植株"
"raspberry bush" = "树莓灌木"
"rat weed" = "杂鼠草"
"red bean vine" = "红豆藤"
"red spinach" = "红菠菜"
"reedgrass" = "茅草"
"rhubarb" = "大黄"
"rice plant" = "稻米植株"
"rope reed" = "绳索苇"
"round lime tree" = "圆橘树"
"rubber tree" = "橡胶树"
"rush" = "灯心草"
"rye" = "黑麦"
"ryegrass" = "绿麦草"
"saguaro" = "巨刺柱"
"sand pear tree" = "沙梨树"
"satintail" = "缎尾草"
"sawgrass" = "锯齿草"
"single-grain wheat" = "单粒小麦"
"sliver barb" = "裂钩草"
"soft wheat" = "软质小麦"
"sorghum" = "高粱"
"soybean plant" = "黄豆植株"
"spelt" = "斯佩尔特麦"
"spinach" = "菠菜"
"spore tree" = "孢子树"
"squash vine" = "西葫芦藤"
"staring eyeball" = "凝视眼球"
"strawberry plant" = "草莓植株"
"string bean plant" = "青豆植株"
"sun berry" = "太阳浆果"
"sweet pod" = "甜豆荚"
"sweet potato plant" = "甘薯植株"
"taro" = "芋头"
"tea tree" = "茶树"
"teff plant" = "苔麸植株"
"tomatillo plant" = "灯笼番茄植株"
"tomato plant" = "番茄植株"
"tower-cap" = "塔菇"
"tunnel tube" = "隧管菌"
"turnip plant" = "芜菁植株"
"two-grain wheat" = "双粒小麦"
"underlichen" = "洞窟地衣"
"urad bean plant" = "尤拉德黑豆植株"
"valley herb" = "山谷香草"
"velvet grass" = "丝绒草"
"walnut tree" = "核桃树"
"watermelon vine" = "西瓜藤"
"whip vine" = "鞭藤"
"white millet plant" = "白粟植株"
"white mountain heather" = "白山石楠"
"white yam plant" = "白薯植株"
"wild carrot plant" = "野胡萝卜植株"
"willow" = "柳树"
"winter melon vine" = "冬瓜藤"
"wormy tendril" = "蠕虫卷须"
"zoysia" = "结缕草"

[[rulesets]]
name = "plural"
[rulesets.rules]
"abaca trees" = "蕉麻树"
"acacias" = "刺槐"
"alders" = "桤树"
"alfalfa" = "苜蓿"
"almond trees" = "扁桃树"
"apple trees" = "苹果树"
"apricot trees" = "杏树"
"arrow bamboo" = "箭竹"
"artichokes" = "洋蓟"
"ashes" = "白蜡树"
"asparagus" = "芦笋"
"avocado trees" = "鳄梨树"
"baby toes succulents" = "幼趾多肉"
"bambara groundnut plants" = "班巴拉花生植株"
"banana trees" = "香蕉树"
"barley" = "大麦"
"bayberry trees" = "杨梅树"
"beet plants" = "甜菜植株"
"bentgrass" = "糠穗草"
"bilberry bushes" = "越橘灌木"
"birches" = "桦树"
"bitter melon vines" = "苦瓜藤"
"bitter orange trees" = "苦橙树"
"bitter vetch" = "苦野豌豆"
"blackberry bushes" = "黑莓灌木"
"black-caps" = "黑菇"
"blade weed" = "刀刃草"
"bloated tubers" = "膨地根"
"blood amaranths" = "血苋"
"blood thorn" = "血荆棘"
"blueberry bushes" = "蓝莓灌木"
"blue sedge" = "蓝苔莎"
"broad bean plants" = "蚕豆植株"
"bubble bulbs" = "泡泡球茎"
"buckwheat" = "荞麦"
"cabbages" = "卷心菜"
"cacao trees" = "可可树"
"candlenuts" = "石栗"
"caper bushes" = "刺山柑灌木"
"carambola trees" = "杨桃树"
"carpetgrass" = "地毯草"
"cashew trees" = "腰果树"
"cassavas" = "木薯"
"cattails" = "猫尾草"
"cave moss" = "洞穴苔藓"
"cave wheat" = "洞穴小麦"
"cedars" = "雪松"
"celery" = "芹菜"
"cherry trees" = "樱桃树"
"chestnuts" = "板栗树"
"chickpea plants" = "鹰嘴豆植株"
"chicory" = "菊苣"
"citron trees" = "香橼树"
"cloudberries" = "云莓"
"coconut palms" = "椰棕榈"
"coffee trees" = "咖啡树"
"common reeds" = "芦苇"
"cottongrass" = "棉草"
"cotton plants" = "棉花植株"
"cowpea plants" = "豇豆植株"
"cranberry vines" = "蔓越莓藤"
"cucumber vines" = "黄瓜藤"
"custard-apple trees" = "番荔枝树"
"dallisgrass" = "雀稗草"
"date palms" = "枣棕榈"
"desert lime trees" = "漠橘树"
"dimple cups" = "窝杯菇"
"dog's tooth grass" = "狗牙草"
"downy grass" = "羽绒草"
"dropseed grass" = "落籽草"
"durian trees" = "榴梿树"
"eggplants" = "茄子"
"elephant-head amaranths" = "象头苋"
"feather trees" = "羽毛树"
"fescue grass" = "细叶草"
"field sedge" = "田野莎草"
"finger lime trees" = "指橘树"
"finger millet plants" = "爪粟植株"
"fisher berries" = "渔夫浆果"
"flax plants" = "亚麻植株"
"floor fungi" = "地真菌"
"fonio plants" = "非尼奥米植株"
"foxtail millet plants" = "狐尾粟植株"
"fungiwoods" = "真菌木"
"garden cress" = "水芹"
"garlic plants" = "大蒜植株"
"ginkgo trees" = "银杏树"
"glumprongs" = "紫影树"
"goblin-caps" = "妖精菇"
"golden bamboo" = "金竹"
"grama" = "格兰马草"
"grape vines" = "葡萄藤"
"guava trees" = "番石榴树"
"hair grass" = "发草"
"hard wheat" = "硬质小麦"
"hazel trees" = "榛树"
"hedge bamboo" = "篱笆竹"
"hemp plants" = "大麻植株"
"hide root" = "匿茎草"
"highwoods" = "极树"
"horned melon vines" = "刺角瓜藤"
"jute plants" = "黄麻植株"
"kaniwa" = "彩藜"
"kapoks" = "木棉树"
"kenaf plants" = "洋麻植株"
"knotgrass" = "绳结草"
"kobold bulbs" = "犬蜥球茎"
"kumquat trees" = "金橘树"
"larches" = "落叶松"
"leeks" = "韭葱"
"lentil plants" = "扁豆植株"
"lesser yam plants" = "小山药植株"
"lettuces" = "生菜"
"lime trees" = "酸橙树"
"Longland grass" = "长岛草"
"long yam plants" = "长山药植株"
"lychee trees" = "荔枝树"
"macadamia trees" = "奶油果树"
"mahoganies" = "褐芯树"
"maize plants" = "玉米植株"
"mango trees" = "芒果树"
"mangroves" = "红树"
"maples" = "枫树"
"marsh thistles" = "沼泽蓟"
"meadow-grass" = "甸草"
"meadowsweet" = "绣线菊"
"mountain avens" = "山蔷薇"
"muck roots" = "淤曲根"
"mung bean plants" = "绿豆植株"
"muskmelon vines" = "甜瓜藤"
"needle grass" = "针草"
"nether-caps" = "下界菇"
"oaks" = "橡树"
"oats" = "燕麦"
"olive trees" = "橄榄树"
"onion plants" = "洋葱植株"
"orange trees" = "橘子树"
"papaya trees" = "番木瓜树"
"papyrus sedges" = "纸莎草"
"paradise nut trees" = "天堂果树"
"parsnip plants" = "防风草植株"
"passion fruit vines" = "百香果藤"
"peach trees" = "桃树"
"peanut plants" = "花生植株"
"pea plants" = "豌豆植株"
"pearl millet plants" = "珍珠粟植株"
"pear trees" = "白梨树"
"pebble plants" = "生石花植株"
"pecan trees" = "碧根果树"
"pendant amaranths" = "吊坠苋"
"pepper plants" = "胡椒植株"
"persimmon trees" = "柿树"
"pig tails" = "猪尾草"
"pineapple plants" = "菠萝植株"
"pines" = "针松"
"plump helmets" = "肉盔菇"
"plum trees" = "李树"
"pomegranate trees" = "石榴树"
"pomelo trees" = "蜜柚树"
"potato plants" = "马铃薯植株"
"prickle berries" = "刺莓"
"purple amaranths" = "紫苋"
"purple moor grass" = "紫泽草"
"purple yam plants" = "紫薯植株"
"quarry bushes" = "矿场灌木"
"quinoa" = "藜麦"
"radish plants" = "小萝卜植株"
"rambutan trees" = "红毛果树"
"ramie plants" = "苎麻植株"
"raspberry bushes" = "树莓灌木"
"rat weed" = "杂鼠草"
"red bean vines" = "红豆藤"
"red spinach" = "红菠菜"
"reedgrass" = "茅草"
"rhubarbs" = "大黄"
"rice plants" = "稻米植株"
"rope reeds" = "绳索苇"
"round lime trees" = "圆橘树"
"rubber trees" = "橡胶树"
"rushes" = "灯心草"
"rye" = "黑麦"
"ryegrass" = "绿麦草"
"saguaros" = "巨刺柱"
"sand pear trees" = "沙梨树"
"satintail" = "缎尾草"
"sawgrass" = "锯齿草"
"single-grain wheat" = "单粒小麦"
"sliver barbs" = "裂钩草"
"soft wheat" = "软质小麦"
"sorghum" = "高粱"
"soybean plants" = "黄豆植株"
"spelt" = "斯佩尔特麦"
"spinach" = "菠菜"
"spore trees" = "孢子树"
"squash vines" = "西葫芦藤"
"staring eyeballs" = "凝视眼球"
"strawberry plants" = "草莓植株"
"string bean plants" = "青豆植株"
"sun berries" = "太阳浆果"
"sweet pods" = "甜豆荚"
"sweet potato plants" = "甘薯植株"
"taro" = "芋头"
"tea trees" = "茶树"
"teff plants" = "苔麸植株"
"tomatillo plants" = "灯笼番茄植株"
"tomato plants" = "番茄植株"
"tower-caps" = "塔菇"
"tunnel tubes" = "隧管菌"
"turnip plants" = "芜菁植株"
"two-grain wheat" = "双粒小麦"
"underlichen" = "洞窟地衣"
"urad bean plants" = "尤拉德黑豆植株"
"valley herbs" = "山谷香草"
"velvet grass" = "丝绒草"
"walnut trees" = "核桃树"
"watermelon vines" = "西瓜藤"
"whip vines" = "鞭藤"
"white millet plants" = "白粟植株"
"white mountain heather" = "白山石楠"
"white yam plants" = "白薯植株"
"wild carrot plants" = "野胡萝卜植株"
"willows" = "柳树"
"winter melon vines" = "冬瓜藤"
"wormy tendrils" = "蠕虫卷须"
"zoysia" = "结缕草"

[[rulesets]]
name = "adjective"
[rulesets.rules]
"abaca tree" = "蕉麻树"
"acacia" = "刺槐"
"alder" = "桤树"
"alfalfa" = "苜蓿"
"almond tree" = "扁桃树"
"apple tree" = "苹果树"
"apricot tree" = "杏树"
"arrow bamboo" = "箭竹"
"artichoke" = "洋蓟"
"ashen" = "白蜡树"
"asparagus" = "芦笋"
"avocado tree" = "鳄梨树"
"baby toes succulent" = "幼趾多肉"
"bambara groundnut plant" = "班巴拉花生植株"
"banana tree" = "香蕉树"
"barley" = "大麦"
"bayberry tree" = "杨梅树"
"beet plant" = "甜菜植株"
"bentgrass" = "糠穗草"
"bilberry bush" = "越橘灌木"
"birchen" = "桦树"
"bitter melon vine" = "苦瓜藤"
"bitter orange tree" = "苦橙树"
"bitter vetch" = "苦野豌豆"
"blackberry bush" = "黑莓灌木"
"black-cap" = "黑菇"
"blade weed" = "刀刃草"
"bloated tuber" = "膨地根"
"blood amaranth" = "血苋"
"blood thorn" = "血荆棘"
"blueberry bush" = "蓝莓灌木"
"blue sedge" = "蓝苔莎"
"broad bean plant" = "蚕豆植株"
"bubble bulb" = "泡泡球茎"
"buckwheat" = "荞麦"
"cabbage" = "卷心菜"
"cacao tree" = "可可树"
"candlenut" = "石栗"
"caper bush" = "刺山柑灌木"
"carambola tree" = "杨桃树"
"carpetgrass" = "地毯草"
"cashew tree" = "腰果树"
"cassava" = "木薯"
"cattail" = "猫尾草"
"cave moss" = "洞穴苔藓"
"cave wheat" = "洞穴小麦"
"cedar" = "雪松"
"celery" = "芹菜"
"cherry tree" = "樱桃树"
"chestnut" = "板栗树"
"chickpea plant" = "鹰嘴豆植株"
"chicory" = "菊苣"
"citron tree" = "香橼树"
"cloudberry" = "云莓"
"coconut palm" = "椰棕榈"
"coffee tree" = "咖啡树"
"common reed" = "芦苇"
"cottongrass" = "棉草"
"cotton plant" = "棉花植株"
"cowpea plant" = "豇豆植株"
"cranberry vine" = "蔓越莓藤"
"cucumber vine" = "黄瓜藤"
"custard-apple tree" = "番荔枝树"
"dallisgrass" = "雀稗草"
"date palm" = "枣棕榈"
"desert lime tree" = "漠橘树"
"dimple cup" = "窝杯菇"
"dog's tooth grass" = "狗牙草"
"downy grass" = "羽绒草"
"dropseed grass" = "落籽草"
"durian tree" = "榴梿树"
"eggplant" = "茄子"
"elephant-head amaranth" = "象头苋"
"feather tree" = "羽毛树"
"fescue grass" = "细叶草"
"field sedge" = "田野莎草"
"finger lime tree" = "指橘树"
"finger millet plant" = "爪粟植株"
"fisher berry" = "渔夫浆果"
"flax plant" = "亚麻植株"
"floor fungus" = "地真菌"
"fonio plant" = "非尼奥米植株"
"foxtail millet plant" = "狐尾粟植株"
"fungiwood" = "真菌木"
"garden cress" = "水芹"
"garlic plant" = "大蒜植株"
"ginkgo tree" = "银杏树"
"glumprong" = "紫影树"
"goblin-cap" = "妖精菇"
"golden bamboo" = "金竹"
"grama" = "格兰马草"
"grape vine" = "葡萄藤"
"guava tree" = "番石榴树"
"hair grass" = "发草"
"hard wheat" = "硬质小麦"
"hazel tree" = "榛树"
"hedge bamboo" = "篱笆竹"
"hemp plant" = "大麻植株"
"hide root" = "匿茎草"
"highwood" = "极树"
"horned melon vine" = "刺角瓜藤"
"jute plant" = "黄麻植株"
"kaniwa" = "彩藜"
"kapok" = "木棉树"
"kenaf plant" = "洋麻植株"
"knotgrass" = "绳结草"
"kobold bulb" = "犬蜥球茎"
"kumquat tree" = "金橘树"
"larch" = "落叶松"
"leek" = "韭葱"
"lentil plant" = "扁豆植株"
"lesser yam plant" = "小山药植株"
"lettuce" = "生菜"
"lime tree" = "酸橙树"
"Longland grass" = "长岛草"
"long yam plant" = "长山药植株"
"lychee tree" = "荔枝树"
"macadamia tree" = "奶油果树"
"mahogany" = "褐芯树"
"maize plant" = "玉米植株"
"mango tree" = "芒果树"
"mangrove" = "红树"
"maple" = "枫树"
"marsh thistle" = "沼泽蓟"
"meadow-grass" = "甸草"
"meadowsweet" = "绣线菊"
"mountain avens" = "山蔷薇"
"muck root" = "淤曲根"
"mung bean plant" = "绿豆植株"
"muskmelon vine" = "甜瓜藤"
"needle grass" = "针草"
"nether-cap" = "下界菇"
"oaken" = "橡树"
"oat" = "燕麦"
"olive tree" = "橄榄树"
"onion plant" = "洋葱植株"
"orange tree" = "橘子树"
"papaya tree" = "番木瓜树"
"papyrus sedge" = "纸莎草"
"paradise nut tree" = "天堂果树"
"parsnip plant" = "防风草植株"
"passion fruit vine" = "百香果藤"
"peach tree" = "桃树"
"peanut plant" = "花生植株"
"pea plant" = "豌豆植株"
"pearl millet plant" = "珍珠粟植株"
"pear tree" = "白梨树"
"pebble plant" = "生石花植株"
"pecan tree" = "碧根果树"
"pendant amaranth" = "吊坠苋"
"pepper plant" = "胡椒植株"
"persimmon tree" = "柿树"
"pig tail" = "猪尾草"
"pine" = "针松"
"pineapple plant" = "菠萝植株"
"plump helmet" = "肉盔菇"
"plum tree" = "李树"
"pomegranate tree" = "石榴树"
"pomelo tree" = "蜜柚树"
"potato plant" = "马铃薯植株"
"prickle berry" = "刺莓"
"purple amaranth" = "紫苋"
"purple moor grass" = "紫泽草"
"purple yam plant" = "紫薯植株"
"quarry bush" = "矿场灌木"
"quinoa" = "藜麦"
"radish plant" = "小萝卜植株"
"rambutan tree" = "红毛果树"
"ramie plant" = "苎麻植株"
"raspberry bush" = "树莓灌木"
"rat weed" = "杂鼠草"
"red bean vine" = "红豆藤"
"red spinach" = "红菠菜"
"reedgrass" = "茅草"
"rhubarb" = "大黄"
"rice plant" = "稻米植株"
"rope reed" = "绳索苇"
"round lime tree" = "圆橘树"
"rubber tree" = "橡胶树"
"rush" = "灯心草"
"rye" = "黑麦"
"ryegrass" = "绿麦草"
"saguaro" = "巨刺柱"
"sand pear tree" = "沙梨树"
"satintail" = "缎尾草"
"sawgrass" = "锯齿草"
"single-grain wheat" = "单粒小麦"
"sliver barb" = "裂钩草"
"soft wheat" = "软质小麦"
"sorghum" = "高粱"
"soybean plant" = "黄豆植株"
"spelt" = "斯佩尔特麦"
"spinach" = "菠菜"
"spore tree" = "孢子树"
"squash vine" = "西葫芦藤"
"staring eyeball" = "凝视眼球"
"strawberry plant" = "草莓植株"
"string bean plant" = "青豆植株"
"sun berry" = "太阳浆果"
"sweet pod" = "甜豆荚"
"sweet potato plant" = "甘薯植株"
"taro" = "芋头"
"tea tree" = "茶树"
"teff plant" = "苔麸植株"
"tomatillo plant" = "灯笼番茄植株"
"tomato plant" = "番茄植株"
"tower-cap" = "塔菇"
"tunnel tube" = "隧管菌"
"turnip plant" = "芜菁植株"
"two-grain wheat" = "双粒小麦"
"underlichen" = "洞窟地衣"
"urad bean plant" = "尤拉德黑豆植株"
"valley herb" = "山谷香草"
"velvet grass" = "丝绒草"
"walnut tree" = "核桃树"
"watermelon vine" = "西瓜藤"
"whip vine" = "鞭藤"
"white millet plant" = "白粟植株"
"white mountain heather" = "白山石楠"
"white yam plant" = "白薯植株"
"wild carrot plant" = "野胡萝卜植株"
"willow" = "柳树"
"winter melon vine" = "冬瓜藤"
"wormy tendril" = "蠕虫卷须"
"zoysia" = "结缕草"
