base = "materials::state"

[[rulesets]]
[rulesets.rules]
"gold dust" = "金粉"
"metal" = "金属"
"native gold dust" = "天然金粉"
"fat" = "脂肪"
"grease" = "油脂"
"cartilage" = "软骨"
"cheese" = "奶酪"
"wood" = "木头"
"sponge" = "海绵"
"saguaro rib wood" = "巨刺柱肋木"
"oak" = "橡树"
"birch" = "桦树"
"{shared}" = "{shared}"

[[rulesets]]
name = "adjective"
[rulesets.rules]
"fatty" = "脂肪"
"greasy" = "油脂"
"cartilaginous" = "软骨"
"cheesy" = "奶酪"
"wooden" = "木制"
"spongy" = "海绵"
"saguaro rib" = "巨刺柱肋木"
"oaken" = "橡木"
"birchen" = "白桦木"
"ashen" = "白蜡木"
"{shared}" = "{shared}"

[[rulesets]]
name = "shared"
[rulesets.rules]
"{shared::^0}{shared::main}{shared::$0}" = "{shared::^0}{shared::main}{shared::$0}"

[[rulesets]]
name = "shared::^0"
optional = true
[rulesets.rules]
"boiling " = "沸腾"
"ground " = "磨碎的"
"pressed " = "压制"
"molten " = "融化的"
"frozen " = "结冻"
"melted " = "熔融"

[[rulesets]]
name = "shared::main"
[rulesets.rules]
"acacia" = "刺槐"
"adamantine" = "精金"
"adder man venom" = "蝰蛇人毒素"
"adder venom" = "蝰蛇毒素"
"alabaster" = "雪花石膏"
"alder" = "桤树"
"alexandrite" = "紫翠玉"
"almandine" = "殷榴石"
"almond wood" = "扁桃木"
"alpaca cheese" = "羊驼奶酪"
"alpaca's milk" = "羊驼奶"
"aluminum" = "铝"
"alunite" = "明矾石"
"amber" = "琥珀"
"amber opal" = "琥珀欧泊"
"amethyst" = "紫水晶"
"andesite" = "安山岩"
"anhydrite" = "硬石膏"
"antler" = "鹿角"
"apple cider" = "苹果西打"
"apple wood" = "苹果木"
"apricot wine" = "杏酒"
"apricot wood" = "杏木"
"aquamarine" = "海蓝宝石"
"artichoke wine" = "洋蓟酒"
"ash" = "灰烬"
"ash glaze" = "灰釉"
"aventurine" = "砂金石"
"avocado wood" = "鳄梨木"
"banana beer" = "香蕉啤酒"
"banded agate" = "条纹玛瑙"
"bandfire opal" = "火纹欧泊"
"bark scorpion man venom" = "树皮蝎人毒素"
"bark scorpion venom" = "树皮蝎毒素"
"barley flour" = "大麦面粉"
"barley wine" = "大麦酒"
"basalt" = "玄武岩"
"bauxite" = "铝土矿"
"bayberry wine" = "杨梅酒"
"bayberry wood" = "杨梅木"
"beetroot wine" = "甜菜根酒"
"bilberry wine" = "越橘酒"
"billon" = "毕朗合金"
"bismuth" = "铋"
"bismuth bronze" = "铋青铜"
"bismuthinite" = "辉铋矿"
"bitter orange wood" = "苦橙木"
"bituminous coal" = "烟煤"
"blackberry wine" = "黑莓酒"
"black bronze" = "乌青铜"
"black-cap" = "黑菇"
"black diamond" = "黑钻石"
"black mamba man venom" = "黑曼巴蛇人毒素"
"black mamba venom" = "黑曼巴蛇毒素"
"black opal" = "黑欧泊"
"black pyrope" = "黑榴石"
"black sand" = "黑沙"
"black zircon" = "黑锆石"
"blood" = "血液"
"blood amaranth beer" = "血苋啤酒"
"blood amaranth flour" = "血苋面粉"
"bloodstone" = "血石"
"blood thorn" = "血荆棘"
"blueberry wine" = "蓝莓酒"
"blue diamond" = "蓝钻石"
"blue garnet" = "蓝榴石"
"blue jade" = "蓝翡翠"
"bone" = "骨头"
"bone meal" = "骨粉"
"bone opal" = "骨质欧泊"
"borax" = "硼砂"
"brain" = "大脑"
"brass" = "黄铜"
"brimstone" = "硫磺"
"bronze" = "青铜"
"brown jasper" = "棕碧玉"
"brown recluse spider man venom" = "棕色遁蛛人毒素"
"brown recluse spider venom" = "棕色遁蛛毒素"
"brown zircon" = "棕锆石"
"buckwheat beer" = "荞麦啤酒"
"buckwheat flour" = "荞麦面粉"
"bud" = "花蕾"
"bumblebee honey" = "大黄蜂蜜"
"bumblebee mead" = "大黄蜂蜜酒"
"bumblebee royal jelly" = "大黄蜂蜂王浆"
"bumblebee venom" = "大黄蜂毒素"
"bumblebee wax" = "大黄蜂蜡"
"bumblebee wax cake" = "大黄蜂蜡饼"
"bushmaster man venom" = "巨蝮人毒素"
"bushmaster venom" = "巨蝮毒素"
"cacao wood" = "可可树"
"calcareous ooze" = "钙质软泥"
"calcite" = "方解石"
"candlenut" = "石栗"
"carambola wine" = "杨桃酒"
"carambola wood" = "杨桃木"
"carnelian" = "红玉髓"
"carrot wine" = "胡萝卜酒"
"cashew wood" = "腰果木"
"cassava beer" = "木薯啤酒"
"cassiterite" = "锡石"
"cat's eye" = "猫眼石"
"cave blob fluid" = "洞穴滴团液体"
"cave floater gas" = "洞穴飘浮者气体"
"cave floater juice" = "洞穴飘浮者汁液"
"cave spider venom" = "洞穴蜘蛛毒素"
"cedar" = "雪松"
"chalk" = "白垩岩"
"cherry opal" = "樱桃欧泊"
"cherry wine" = "樱桃酒"
"cherry wood" = "樱桃木"
"chert" = "角岩"
"chestnut" = "板栗树"
"chitin" = "甲壳"
"chromite" = "铬铁矿"
"chrysoberyl" = "金绿玉"
"chrysocolla" = "硅孔雀石"
"chrysoprase" = "绿玉髓"
"cinnabar" = "辰砂"
"cinnamon grossular" = "褐榴石"
"citrine" = "黄水晶"
"citron wood" = "香橼木"
"claro opal" = "烟欧泊"
"clay" = "黏土"
"clay loam" = "黏质壤土"
"claystone" = "黏土岩"
"clear diamond" = "透明钻石"
"clear garnet" = "透明榴石"
"clear glass" = "透明玻璃"
"clear tourmaline" = "透明碧玺"
"clear zircon" = "透明锆石"
"coal" = "煤炭"
"coal slush" = "煤炭渣"
"cobaltite" = "辉钴矿"
"coconut palm" = "椰棕榈"
"coffee wood" = "咖啡木"
"condensed iron man gas" = "稠密铁人气体"
"conglomerate" = "砾岩"
"copper" = "铜"
"copperhead snake man venom" = "铜头蛇人毒素"
"copperhead snake venom" = "铜头蛇毒素"
"coral" = "珊瑚"
"corrupted blood" = "腐败血液"
"cotton" = "棉花"
"cotton seed" = "棉花种子"
"cottonseed oil" = "棉花籽油"
"cottonseed oil soap" = "棉花籽油肥皂"
"cow cheese" = "牛奶奶酪"
"cow's milk" = "牛奶"
"cranberry wine" = "蔓越莓酒"
"cryolite" = "冰晶石"
"crystal glass" = "水晶玻璃"
"crystal opal" = "水晶欧泊"
"custard-apple cider" = "番荔枝西打"
"custard-apple wood" = "番荔枝木"
"cuttlefish ink" = "墨鱼墨汁"
"cuttlefish man ink" = "墨鱼人墨汁"
"dacite" = "英安岩"
"date palm wood" = "椰枣棕榈木"
"date wine" = "椰枣酒"
"demantoid" = "翠榴石"
"dendritic agate" = "枝纹玛瑙"
"desert lime wood" = "漠橘木"
"dimple dye" = "窝杯染料"
"diorite" = "闪长岩"
"dirt" = "土壤"
"dolomite" = "白云石"
"donkey cheese" = "驴奶奶酪"
"donkey's milk" = "驴奶"
"durian wine" = "榴梿酒"
"durian wood" = "榴梿木"
"dwarven ale" = "矮人精酿"
"dwarven beer" = "矮人麦啤"
"dwarven cheese" = "矮人奶酪"
"dwarven milk" = "矮人奶"
"dwarven rum" = "矮人朗姆酒"
"dwarven sugar" = "矮人砂糖"
"dwarven syrup" = "矮人糖浆"
"dwarven wheat flour" = "矮人小麦粉"
"dwarven wine" = "矮人酒"
"earthenware" = "瓦陶"
"eggshell" = "蛋壳"
"egg white" = "蛋白"
"egg yolk" = "蛋黄"
"electrum" = "琥珀金"
"emerald" = "祖母绿宝石"
"emerald dye" = "宝石绿染料"
"eye tissue" = "眼部组织"
"faint yellow diamond" = "微黄钻石"
"feather" = "羽毛"
"feather wood" = "羽毛树"
"fiber" = "纤维"
"filth" = "污垢"
"filth slush" = "污垢泥"
"fine pewter" = "精白锡"
"finger lime wood" = "指橘木"
"finger millet beer" = "爪粟啤酒"
"finger millet flour" = "爪粟面粉"
"fire agate" = "火玛瑙"
"fire clay" = "火黏土"
"fire opal" = "火欧泊"
"fisher berry wine" = "渔夫浆果酒"
"flames" = "火焰"
"flax flour" = "亚麻面粉"
"flax seed" = "亚麻种子"
"flesh" = "血肉"
"flower" = "花"
"fluff" = "绒毛"
"fonio beer" = "非尼奥啤酒"
"fonio flour" = "非尼奥面粉"
"fortification agate" = "城垒玛瑙"
"foxtail millet beer" = "狐尾粟啤酒"
"foxtail millet flour" = "狐尾粟面粉"
"fruit" = "果实"
"fungiwood" = "真菌木"
"fur" = "毛皮"
"gabbro" = "辉长岩"
"galena" = "方铅矿"
"garnierite" = "硅镁镍矿"
"giant adder venom" = "巨型蝰蛇毒素"
"giant bark scorpion venom" = "巨型树皮蝎毒素"
"giant black mamba venom" = "巨型黑曼巴蛇毒素"
"giant brown recluse spider venom" = "巨型棕色遁蛛毒素"
"giant bushmaster venom" = "巨型巨蝮毒素"
"giant cave spider venom" = "巨型洞穴蜘蛛毒素"
"giant copperhead snake venom" = "巨型铜头蛇毒素"
"giant cuttlefish ink" = "巨型墨鱼墨汁"
"giant gila monster venom" = "巨型毒蜥毒素"
"giant kangaroo cheese" = "巨型袋鼠奶酪"
"giant kangaroo's milk" = "巨型袋鼠奶"
"giant king cobra venom" = "巨型眼镜王蛇毒素"
"giant octopus ink" = "巨型章鱼墨汁"
"giant one-humped camel cheese" = "巨型单峰骆驼奶酪"
"giant one-humped camel's milk" = "巨型单峰骆驼奶"
"giant platypus venom" = "巨型鸭嘴兽毒素"
"giant rattlesnake venom" = "巨型响尾蛇毒素"
"giant squid ink" = "巨型鱿鱼墨汁"
"giant tapir cheese" = "巨型貘奶酪"
"giant tapir's milk" = "巨型貘奶"
"giant two-humped camel cheese" = "巨型双峰骆驼奶酪"
"giant two-humped camel's milk" = "巨型双峰骆驼奶"
"gila monster man venom" = "毒蜥人毒素"
"gila monster venom" = "毒蜥毒素"
"ginkgo wood" = "银杏木"
"gizzard tissue" = "砂囊组织"
"glumprong" = "紫影树"
"gneiss" = "片麻岩"
"gnomeblight" = "地精枯萎病"
"goat cheese" = "山羊奶奶酪"
"goat's milk" = "山羊奶"
"goblin-cap" = "妖精菇"
"gold" = "金"
"golden beryl" = "金柱石"
"golden salve" = "金色药膏"
"gold opal" = "金欧泊"
"goo" = "稠血"
"goshenite" = "白柱石"
"granite" = "花岗岩"
"graphite" = "石墨"
"gray chalcedony" = "灰玉髓"
"green diamond" = "绿钻石"
"green glass" = "绿玻璃"
"green jade" = "绿翡翠"
"green tourmaline" = "绿碧玺"
"green zircon" = "绿锆石"
"grime" = "尘垢"
"guava wine" = "番石榴酒"
"guava wood" = "番石榴木"
"gut" = "肠"
"gutter cruor" = "凝血酒"
"gypsum" = "软石膏"
"gypsum plaster" = "石膏灰泥"
"hair" = "毛发"
"hard wheat beer" = "硬质小麦啤"
"hard wheat flour" = "硬质小麦面粉"
"harlequin opal" = "斑斓欧泊"
"hazel wood" = "榛木"
"heart tissue" = "心脏组织"
"heliodor" = "绿柱石"
"helmet snake venom" = "头盔蛇毒素"
"hematite" = "赤铁矿"
"hemp" = "大麻"
"hemp flour" = "大麻面粉"
"hemp seed" = "大麻种子"
"hempseed oil" = "大麻籽油"
"hempseed oil soap" = "大麻籽油肥皂"
"highwood" = "极树"
"honey bee honey" = "蜜蜂蜜"
"honey bee royal jelly" = "蜜蜂蜂王浆"
"honey bee venom" = "蜜蜂毒素"
"honey bee wax" = "蜂蜡"
"honey bee wax cake" = "蜂蜡饼"
"honey yellow beryl" = "蜜黄柱石"
"hoof" = "蹄"
"horn" = "角"
"hornblende" = "角闪石"
"horn silver" = "角银矿"
"horse cheese" = "马奶奶酪"
"horse's milk" = "马奶"
"ice" = "冰"
"ichor" = "体液"
"ilmenite" = "钛铁矿"
"indigo tourmaline" = "靛蓝碧玺"
"iron" = "铁"
"iron man gas" = "铁人气体"
"ivory" = "长牙"
"jasper opal" = "碧玉欧泊"
"jelly opal" = "冻胶欧泊"
"jet" = "煤玉"
"jute" = "黄麻纤维"
"kangaroo cheese" = "袋鼠奶酪"
"kangaroo man cheese" = "袋鼠人奶酪"
"kangaroo man's milk" = "袋鼠人奶"
"kangaroo's milk" = "袋鼠奶"
"kaniwa beer" = "彩藜啤酒"
"kaniwa flour" = "彩藜面粉"
"kaolinite" = "高岭石"
"kapok" = "木棉树"
"kenaf" = "洋麻"
"kenaf seed" = "洋麻种子"
"kenaf seed oil" = "洋麻籽油"
"kenaf seed oil soap" = "洋麻籽油肥皂"
"kidney tissue" = "肾组织"
"kimberlite" = "金伯利岩"
"king cobra man venom" = "眼镜王蛇人毒素"
"king cobra venom" = "眼镜王蛇毒素"
"kumquat wood" = "金橘木"
"kunzite" = "紫锂辉石"
"lace agate" = "蕾丝玛瑙"
"lapis lazuli" = "青金石"
"larch" = "落叶松"
"lavender jade" = "紫翡翠"
"lay pewter" = "劣白锡"
"lead" = "铅"
"leaf" = "叶"
"leather" = "皮革"
"levin opal" = "雷电欧泊"
"light yellow diamond" = "亮黄钻石"
"lignite" = "褐煤"
"limestone" = "石灰岩"
"lime wood" = "酸橙木"
"limonite" = "褐铁矿"
"linen" = "亚麻纤维"
"linseed oil" = "亚麻籽油"
"linseed oil soap" = "亚麻籽油肥皂"
"liquid fire" = "液态火焰"
"liver tissue" = "肝脏组织"
"llama cheese" = "无峰驼奶酪"
"llama's milk" = "无峰驼奶"
"loam" = "壤土"
"loamy sand" = "壤砂"
"Longland beer" = "长岛啤酒"
"Longland flour" = "长岛草面粉"
"lung tissue" = "肺部组织"
"lychee wine" = "荔枝酒"
"lychee wood" = "荔枝木"
"lye" = "碱液"
"lye slush" = "碱液泥"
"macadamia wood" = "奶油果木"
"magma" = "岩浆"
"magnetite" = "磁铁矿"
"mahogany" = "褐芯树"
"maize beer" = "玉米啤酒"
"maize flour" = "玉米面粉"
"malachite" = "孔雀石"
"mango wine" = "芒果酒"
"mango wood" = "芒果树"
"mangrove" = "红树"
"maple" = "枫树"
"marble" = "大理石"
"marcasite" = "白铁矿"
"mead" = "蜜酒"
"melanite" = "墨榴石"
"mica" = "云母"
"microcline" = "微斜长石"
"milk of lime" = "石灰乳"
"milk opal" = "乳欧泊"
"milk quartz" = "乳石英"
"mog juice" = "跳虫肉汁"
"moonstone" = "月长石"
"morganite" = "摩根石"
"morion" = "黑水晶"
"moss agate" = "苔藓玛瑙"
"moss opal" = "苔藓欧泊"
"mud" = "淤泥"
"mudstone" = "泥岩"
"muscle" = "肌肉"
"mushroom" = "蘑菇"
"nail" = "指甲"
"native aluminum" = "天然铝矿"
"native copper" = "天然铜矿"
"native gold" = "天然金矿"
"native platinum" = "天然铂矿"
"native silver" = "天然银矿"
"nervous tissue" = "神经组织"
"nether-cap" = "下界菇"
"nickel" = "镍"
"nickel silver" = "镍银"
"oat flour" = "燕麦面粉"
"obsidian" = "黑曜石"
"octopus ink" = "章鱼墨汁"
"octopus man ink" = "章鱼人墨汁"
"olive fruit" = "橄榄果"
"olive oil" = "橄榄油"
"olive oil soap" = "橄榄油皂"
"olive pomace" = "橄榄果渣"
"olive wood" = "橄榄木"
"olivine" = "橄榄岩"
"one-humped camel cheese" = "单峰骆驼奶酪"
"one-humped camel man cheese" = "单峰骆驼人奶酪"
"one-humped camel man's milk" = "单峰骆驼人奶"
"one-humped camel's milk" = "单峰骆驼奶"
"onyx" = "缟玛瑙"
"onyx opal" = "缟纹欧泊"
"orange wood" = "橘子木"
"orpiment" = "雌黄"
"orthoclase" = "正长石"
"pancreatic tissue" = "胰腺组织"
"papaya wine" = "番木瓜酒"
"papaya wood" = "番木瓜木"
"papyrus" = "纸莎草"
"paradise nut wood" = "天堂果木"
"parchment" = "羊皮纸"
"parsnip wine" = "防风草酒"
"passion fruit wine" = "百香果酒"
"peach cider" = "桃子西打"
"peach wood" = "桃木"
"pearlash" = "珍珠灰"
"pearl millet beer" = "珍珠粟啤酒"
"pearl millet flour" = "珍珠粟面粉"
"pear wood" = "梨木"
"peat" = "泥炭"
"pecan wood" = "碧根果木"
"pelagic clay" = "深海黏土"
"pendant amaranth beer" = "吊坠苋啤酒"
"pendant amaranth flour" = "吊坠苋面粉"
"periclase" = "方镁石"
"peridot" = "橄榄石"
"perry" = "梨酒"
"persimmon wine" = "柿酒"
"persimmon wood" = "柿木"
"petrified wood" = "石化木"
"phantom spider venom" = "幻影蜘蛛毒素"
"phyllite" = "千枚岩"
"picture jasper" = "图画碧玉"
"pig cheese" = "猪奶奶酪"
"pig iron" = "生铁"
"pig's milk" = "猪奶"
"pig tail" = "猪尾草"
"pine" = "针松"
"pineapple opal" = "凤梨欧泊"
"pineapple wine" = "菠萝酒"
"pinfire opal" = "星火欧泊"
"pink garnet" = "粉红榴石"
"pink jade" = "粉红翡翠"
"pink tourmaline" = "粉红碧玺"
"pipe opal" = "管纹欧泊"
"pitchblende" = "沥青铀矿"
"plant" = "植物"
"platinum" = "铂"
"platypus man venom" = "鸭嘴兽人毒素"
"platypus venom" = "鸭嘴兽毒素"
"plume agate" = "羽毛玛瑙"
"plump helmet man tissue" = "肉盔菇人组织"
"plum wine" = "李子酒"
"plum wood" = "李子木"
"pomegranate wine" = "石榴酒"
"pomegranate wood" = "石榴木"
"pomelo wood" = "蜜柚木"
"porcelain" = "瓷器"
"potash" = "草碱"
"potash slush" = "草碱渣"
"potato wine" = "马铃薯酒"
"prase" = "苍绿石英"
"prase opal" = "苍绿欧泊"
"precious fire opal" = "贵火欧泊"
"prickle berry wine" = "刺莓酒"
"puddingstone" = "布丁岩"
"pudge" = "球脂"
"purple amaranth beer" = "紫苋啤酒"
"purple amaranth flour" = "紫苋面粉"
"purple spinel" = "紫尖晶石"
"pus" = "脓"
"pyrite" = "黄铁矿"
"pyrolusite" = "软锰矿"
"quartzite" = "石英岩"
"quicklime" = "生石灰"
"quinoa beer" = "藜麦啤酒"
"quinoa flour" = "藜麦面粉"
"radish wine" = "小萝卜酒"
"rambutan wine" = "红毛丹酒"
"rambutan wood" = "红毛丹木"
"ramie" = "苎麻"
"raspberry wine" = "树莓酒"
"rattlesnake man venom" = "响尾蛇人毒素"
"rattlesnake venom" = "响尾蛇毒素"
"raw adamantine" = "原始精金"
"realgar" = "雄黄"
"red beryl" = "红柱石"
"red diamond" = "红钻石"
"red flash opal" = "红闪欧泊"
"red grossular" = "红榴石"
"red pyrope" = "赤榴石"
"redroot dye" = "赤根染料"
"red sand" = "红沙"
"red spinel" = "红尖晶石"
"red tourmaline" = "红碧玺"
"red zircon" = "红锆石"
"reindeer cheese" = "驯鹿奶酪"
"reindeer's milk" = "驯鹿奶"
"resin opal" = "脂光欧泊"
"rhodolite" = "朱榴石"
"rhyolite" = "流纹岩"
"rice beer" = "稻米啤酒"
"rice flour" = "稻米面粉"
"river spirits" = "河川烈酒"
"rock" = "岩石"
"rock crystal" = "岩石水晶"
"rock nut" = "石头坚果"
"rock nut oil" = "石头坚果油"
"rock nut soap" = "石头坚果皂"
"rock salt" = "岩盐"
"rope reed" = "绳索苇"
"rose gold" = "玫瑰金"
"rose quartz" = "蔷薇石英"
"round lime wood" = "圆橘木"
"rubber wood" = "橡胶树"
"rubicelle" = "橙尖晶石"
"ruby" = "红宝石"
"rutile" = "金红石"
"rye beer" = "黑麦啤酒"
"rye flour" = "黑麦面粉"
"salt" = "盐"
"saltpeter" = "硝石"
"sand" = "沙"
"sand pear cider" = "沙梨西打"
"sand pear wood" = "沙梨木"
"sandstone" = "砂岩"
"sandy clay" = "砂质黏土"
"sandy clay loam" = "砂质黏壤土"
"sandy loam" = "砂质壤土"
"sapphire" = "蓝玉"
"sard" = "褐玉髓"
"sardonyx" = "缠丝玛瑙"
"satinspar" = "纤维石膏"
"scale" = "鳞片"
"schist" = "片岩"
"schorl" = "黑碧玺"
"seed" = "种子"
"selenite" = "透明石膏"
"serpentine" = "蛇纹石"
"serpent man venom" = "毒蛇人毒素"
"sewer brew" = "阴沟佳酿"
"shale" = "页岩"
"sheep cheese" = "羊奶奶酪"
"sheep's milk" = "羊奶"
"shell" = "壳"
"shell opal" = "贝壳欧泊"
"siliceous ooze" = "硅藻软泥"
"silk" = "丝绸"
"silt" = "淤泥"
"silt loam" = "粉质壤土"
"siltstone" = "粉砂岩"
"silty clay" = "粉质粘土"
"silty clay loam" = "粉质黏壤土"
"silver" = "银"
"sinew" = "肌腱"
"single-grain wheat beer" = "单粒小麦啤"
"single-grain wheat flour" = "单粒小麦面粉"
"skin" = "皮肤"
"slade" = "基岩"
"slate" = "板岩"
"sliver dye" = "裂钩染料"
"slush" = "泥地"
"smoky quartz" = "烟石英"
"snow" = "雪"
"soap" = "肥皂"
"soft wheat beer" = "软质小麦啤"
"soft wheat flour" = "软质小麦面粉"
"sorghum beer" = "高粱啤酒"
"sorghum flour" = "高粱面粉"
"spelt beer" = "斯佩尔特麦啤"
"spelt flour" = "斯佩尔特麦面粉"
"sphalerite" = "闪锌矿"
"spine" = "脊椎"
"spit" = "唾液"
"spleen tissue" = "脾组织"
"spore tree" = "孢子树"
"squid ink" = "鱿鱼墨汁"
"squid man ink" = "鱿鱼人墨汁"
"star ruby" = "星彩红宝石"
"star sapphire" = "星彩蓝玉"
"steam" = "蒸汽"
"steel" = "钢"
"sterling silver" = "标准银"
"stibnite" = "辉锑矿"
"stomach tissue" = "胃组织"
"stoneware" = "炻瓷"
"strawberry wine" = "草莓酒"
"sunshine" = "日光酒"
"sunstone" = "日长石"
"swamp whiskey" = "沼泽威士忌"
"sweat" = "汗液"
"sweet potato wine" = "甘薯酒"
"sylvite" = "钾岩"
"talc" = "滑石"
"tallow" = "脂油"
"tanzanite" = "坦桑石"
"tapir cheese" = "貘奶酪"
"tapir man cheese" = "貘人奶酪"
"tapir man's milk" = "貘人奶"
"tapir's milk" = "貘奶"
"tears" = "眼泪"
"tea wood" = "茶木"
"teff beer" = "苔麸啤酒"
"teff flour" = "苔麸面粉"
"tetrahedrite" = "黝铜矿"
"tigereye" = "虎眼石"
"tiger iron" = "虎铁石"
"tin" = "锡"
"tin glaze" = "锡釉"
"tomatillo wine" = "灯笼番茄酒"
"tomato wine" = "番茄酒"
"tooth" = "牙齿"
"topaz" = "黄玉"
"topazolite" = "黄榴石"
"tower-cap" = "塔菇"
"trifle pewter" = "廉白锡"
"tsavorite" = "沙弗莱石"
"tube agate" = "管脉玛瑙"
"tuber beer" = "地根啤酒"
"tunnel tube" = "隧管菌"
"turnip wine" = "芜菁酒"
"turquoise" = "绿松石"
"two-grain wheat beer" = "双粒小麦啤"
"two-grain wheat flour" = "双粒小麦面粉"
"two-humped camel cheese" = "双峰骆驼奶酪"
"two-humped camel man cheese" = "双峰骆驼人奶酪"
"two-humped camel man's milk" = "双峰骆驼人奶"
"two-humped camel's milk" = "双峰骆驼奶"
"unknown boiling creature substance" = "未知沸腾生物质"
"unknown boiling plant substance" = "未知沸腾植物衍生品"
"unknown boiling substance" = "未知沸腾物质"
"unknown creature" = "未知生物"
"unknown creature substance" = "未知生物质"
"unknown frozen" = "未知冻结"
"unknown frozen creature" = "未知生物质"
"unknown frozen creature substance" = "未知冻结生物质"
"unknown frozen plant" = "未知冻结植属"
"unknown frozen plant substance" = "未知冻结植物衍生品"
"unknown frozen substance" = "未知冻结物质"
"unknown plant substance" = "未知植物衍生品"
"unknown pressed frozen creature substance" = "未知压实冻结生物质"
"unknown pressed frozen plant substance" = "未知压实冻结植物衍生品"
"unknown slush" = "未知污水"
"unknown substance" = "未知物质"
"variscite" = "磷铝石"
"vellum" = "皮纸"
"violet spessartine" = "紫榴石"
"vomit" = "呕吐物"
"walnut wood" = "胡桃木"
"water" = "水"
"water buffalo cheese" = "水牛奶奶酪"
"water buffalo's milk" = "水牛奶"
"wax opal" = "蜡质欧泊"
"whip vine flour" = "鞭藤面粉"
"whip wine" = "长鞭酒"
"white chalcedony" = "白玉髓"
"white jade" = "白翡翠"
"white millet beer" = "白粟啤酒"
"white millet flour" = "白粟面粉"
"white opal" = "白欧泊"
"white sand" = "白沙"
"willow" = "柳树"
"wine" = "葡萄酒"
"wood opal" = "木欧泊"
"wool" = "绒线"
"yak cheese" = "牦牛奶酪"
"yak's milk" = "牦牛奶"
"yellow diamond" = "黄钻石"
"yellow grossular" = "缃榴石"
"yellow jasper" = "黄碧玉"
"yellow sand" = "黄沙"
"yellow spessartine" = "橙榴石"
"yellow zircon" = "黄锆石"
"zinc" = "锌"

[[rulesets]]
name = "shared::$0"
optional = true
[rulesets.rules]
" paste" = "膏"
" powder" = "粉末"
" press cake" = "压缩饼"
" slurry" = "浆"
" paper" = "纸"
