base = "tasks"

[[rulesets]]
[rulesets.rules]
"{^0}{main}" = "{^0}{main}"

[[rulesets]]
name = "^0"
[rulesets.rules]
"Assemble" = "组装"
"Forge" = "打造"
"Make" = "制作"

[[rulesets]]
name = "main"
[rulesets.rules]
"{::items}" = "{::items}"
