base = "items::backpack"

[[rulesets]]
[rulesets.rules]
"{::items::prefix::maybe_equipment_size}{^0}{main}" = "{::items::prefix::maybe_equipment_size}{^0}{main}"

[[rulesets]]
name = "^0"
optional = true
[rulesets.rules]
"{::materials::adjective} " = "{::materials::adjective}"

[[rulesets]]
name = "main"
[rulesets.rules]
"backpack" = "背包"
"backpacks" = "背包"
