base = "items::bag"

[[rulesets]]
[rulesets.rules]
"{^0}{main}" = "{^0}{main}"
"{::items} Bag{$0}" = "{::items}袋子{$0}"

[[rulesets]]
name = "$0"
optional = true
[rulesets.rules]
" ({::materials::adjective})" = " ({::materials::adjective})"

[[rulesets]]
name = "^0"
optional = true
[rulesets.rules]
"{::materials::adjective} " = "{::materials::adjective}"

[[rulesets]]
name = "main"
[rulesets.rules]
"bag" = "袋子"
"bags" = "袋子"
