base = "items::cabinet"

[[rulesets]]
[rulesets.rules]
"{^0}{main}" = "{^0}{main}"

[[rulesets]]
name = "^0"
optional = true
[rulesets.rules]
"{::materials::adjective} " = "{::materials::adjective}"

[[rulesets]]
name = "main"
[rulesets.rules]
"cabinet" = "柜子"
"cabinets" = "柜子"
