base = "items::cheese"

[[rulesets]]
[rulesets.rules]
"{^0}{main}" = "{^0}{main}"

[[rulesets]]
name = "^0"
optional = true
[rulesets.rules]
"rotten " = "变质的"

[[rulesets]]
name = "main"
[rulesets.rules]
"{::materials} " = "{::materials}"
"cheese" = "奶酪"
