base = "items::corpse"

[[rulesets]]
[rulesets.rules]
"{^0}{main}" = "{^0}{main}"

[[rulesets]]
name = "^0"
optional = true
[rulesets.rules]
"rotten " = "腐烂的"

[[rulesets]]
name = "main"
[rulesets.rules]
"corpse" = "尸体"
"corpses" = "尸体"
