base = "items::flask"

[[rulesets]]
[rulesets.rules]
"{^0}{main}" = "{^0}{main}"

[[rulesets]]
name = "^0"
optional = true
[rulesets.rules]
"{::materials::adjective} " = "{::materials::adjective}"

[[rulesets]]
name = "main"
[rulesets.rules]
"flask" = "携带瓶"
"flasks" = "携带瓶"
"vial" = "小瓶"
"vials" = "小瓶"
"waterskin" = "水袋"
"waterskins" = "水袋"
