base = "items::goblet"

[[rulesets]]
[rulesets.rules]
"{^0}{main}" = "{^0}{main}"

[[rulesets]]
name = "^0"
optional = true
[rulesets.rules]
"{::materials::adjective} " = "{::materials::adjective}"

[[rulesets]]
name = "main"
[rulesets.rules]
"goblet" = "高脚杯"
"goblets" = "高脚杯"
"cup" = "茶杯"
"mug" = "柄杯"
