base = "items::instrument"

[[rulesets]]
[rulesets.rules]
"{^0}{main}" = "{^0}{main}"

[[rulesets]]
name = "^0"
optional = true
[rulesets.rules]
"{::materials::adjective} " = "{::materials::adjective}"

[[rulesets]]
name = "main"
[rulesets.rules]
"musical instrument" = "乐器"
"musical instruments" = "乐器"
