base = "items::plant"

[[rulesets]]
[rulesets.rules]
"{^0}{main}" = "{^0}{main}"

[[rulesets]]
name = "^0"
optional = true
[rulesets.rules]
"withered " = "枯萎的"

[[rulesets]]
name = "main"
[rulesets.rules]
"plants" = "植物"
"{::plants::name::singular}" = "{::plants::name::singular}"
"{::plants::name::plural}" = "{::plants::name::plural}"
