base = "items::rock"

[[rulesets]]
[rulesets.rules]
"{^0}{main}" = "{^0}{main}"

[[rulesets]]
name = "^0"
[rulesets.rules]
"small " = "小"

[[rulesets]]
name = "main"
[rulesets.rules]
"{::materials}" = "{::materials}"
"rock" = "石子"
